### PR TITLE
issue #37, new strict_users setting to restrict usage of the plugin to logged in users

### PR DESCRIPTION
**Pull request by kmoouni**
Hi Michael,
this is how we've made the change - 
now gives a die message if used outside of moodle.

### CODE REVIEW

**Comment by michael-milette** [comment]
Hi @kmoouni,

Thank you and congratulations with your first pull request. I welcome your recommended changes. For consistency and the highest quality of coding, please review my comments below and let me know if you have any questions. I will be happy to work with you to resolved these issues and then gladly consider your pull request.

== CHANGELOG.md

Avoid the technobable. We need to keep in mind that not all adminstrators have a technial background. Please change this to:

    ## [0.8.3] - 2017-11-23
    ### Added
    - New Require Login setting - requires user to be logged-in in order to submit a form.

== README.md

Avoid the technobable and promote best practices. Please change it to:

    ### Requiring login

    The `Require login` setting requires that users be logged-in in order to be able to submit the form. If a form is submitted and the user is not logged-in, he/she will be prompted to login. If you require users to be logged-in, it is also highly recommended that you also place your form on a page which is only accessible to logged-in users. Guest users are not considered to be logged-in.

== index.php

You previously indicated that your intention was to have users redirected to the login page. Your code doesn't do that. Have you changed your mind about that? 

1) If this is still your intention, you will need to re-think how you are solving the problem.

2) If you have decided not to send them to the login page, the code should not end in a die(with an error message). Please look at how spam detection failures work and have take the same approach.

3) When testing a Moodle checkbox setting, please use !empty(get_config('local_contact', 'loginrequired')) instead of just get_config('local_contact', 'loginrequired'). Moodle doens't have automatic default values. This is a common assumption made by developers because the settings pages actually say "Default: ...".

4) Your code fails the [Moodle Code-checker](https://moodle.org/plugins/local_codechecker) and therefore the also the [Moodle Coding Style guidelines](https://docs.moodle.org/dev/Coding_style). Please test it and fix any issues it reports.

== lang/en/local_contact.php

Keep it simple. Please change your strings to:

    $string['loginrequired'] = 'Login required';
    $string['loginrequired_description'] = 'Only allow logged-in users to submit the Contact forms. Guests are not considered to be logged-in.';

On a side note, to be consistent with the format used for other similar variables, the 'strictusers_desc' variable should have been called 'strictusers_description'. Strictly speaking, I too made a mistake when naming these variables. For future reference, according to the Moodle Coding Style guidelines, underscores should only be used in classes, constants, method and function names. It doesn't actually explicitly say that you shouldn't use underscores in the guidelines however, if you browse through existing source code and the language files themselves, you will noticed that most are like that. I suspect that the ones with underscores are probably pretty old. Because other variables in this language file use an underscore for the description strings, we should use it here too for consistency.

As for the error message:

    $string['strictusers_denied'] = 'Failed to send e-mail because you are not logged in.';

If you are redirecting them to the login page, this message is not required.

If you are not redirecting them, then one of the following error messages, already defined in Moodle's language files, should be used instead using the current established error reporting method.

    From error.php: $string['mustbeloggedin'] = 'You must be logged in to do this';
    - OR -
    From webservice.php: $string['loginrequired'] = 'Restricted to logged-in users';

On the plus side, I would like to commend you for using language strings instead of hard coding text. A lot of new developers would have just put a hard coded string. With that said, if the message is only going to be visible in debug mode, I believe it should actually be hard coded in English only so that the exact error message can be looked up in the documentation to help people figure out what the problem is and how to address it.

== settings.php

1) Please put the spaces back that you removed at the beginning of lines 19 to 24 so that the coding style is consistent with [PHPDoc](http://docs.phpdoc.org/references/phpdoc/basic-syntax.html) and therefore Moodle coding style guidelines. Be sure to test your modification using the [Moodle PHPdoc check tool](https://moodle.org/plugins/local_moodlecheck).

2) Please split up your new $settings->add(...) line in the same way that other settings on this the same source code so that it is consistent with existing coding style. I know it can all be done in one line but readability is paramount to promoting sustainability, readability and avoiding technical debt. Just because you can do something doesn't mean you should.

3) Add a comment above that section to indicate what it is for.

4) Please review the [Moodle Coding Style guidelines](https://docs.moodle.org/dev/Coding_style). The indentation of wrapped lines should be 8 spaces, not 4.

== version.php

No further changes are required... unless you change the date in the CHANGELOG.md file. :-)

Thanks again for your efforts. While some of these are not necessarily strictly required, they are good coding practices and help you become a better developer. This is why I am taking the time to help you. It made a difference for me when people helped me when I first started developing for Moodle. It will also make it easier to the plugin into the future.

Best regards,

Michael

**Comment by kmoouni** [comment]
Hi Michael,
I've implemented your useful feedback, so hopefully these changes should fit into the style of the code. 
If the emailing is rejected the plugin redirects to a nicer error page with a continue link as per the existing anti-spam approach.

**Comment by michael-milette** [comment]
Hi Kevin,

Thank you for making some of the changes. You are making good progress and I encourage you to continue your efforts. You may not realize just how close you are to finishing. With that said, you are still trying to take shortcuts.

I can tell by your coding style that, as I previously recommended and documented in CONTRIBUTING.md, you did not read the [Coding Style guidelines]( [Code Style guide](https://docs.moodle.org/dev/Coding_style)) or make use of the [Moodle Code Checker plugin](https://moodle.org/plugins/local_codechecker) to verify your code and resolve any issues it reports. If you are not sure how to do this, please ask questions instead of just ignoring this recommendation. I will be happy to help you. :-)

When applying the Moodle coding style, don't rely exclusively on the code checker plugin. You must to follow the guide first. The code checker plugin is there to help support the coding style and does a nice quick check. I use it all the time to make sure I didn't miss anything. It often find small issues that I missed and that's ok. That is what it is for - to help you. However, when I upload new versions of the plugin to Moodle.org, it goes through a much more comprehensive test that checks it against all of the coding standards, not just a subset. That is why you must read and follow the guide. Not just what it says in the text but also pay attention to way examples are formatted. You will find that most of the source code in Moodle is formatted exactly that way. Notice the differences between your coding style and what is in the guide. 

It's not that your code won't work. It's about maintainability. You may find it easy to read your code but others will need to when they maintain it or contribute in the future. Some of the benefits of following the style guide include:

- Your code will be more understandable and maintainable by others.
- It will reduce the chances of errors accidentally slipping in.
- Debugging will be easier.
- It will make it easier for you to notice when something doesn't look quite right.
- It will help you become a better developer.

Because a lot of the documentation for developing in Moodle is in the source code itself, coding in a way that is consistent with the Moodle Code Style guide also makes it easier to find code examples and understand how the code works down the road.

I could tell you exactly what the current coding style problems are but I really want to encourage you to learn this time by reading and becoming familiar with the Code Style guide and taking the time to install and try out the Code Checker plugin. That said, what I will tell you is that there are more issues than the Code Checker plugin reports. Don't worry, it's not as bad or as overwhelming as you might think. I know you can do this. Let me know if you have questions or need help.

Now, as for what your code does...

The message and the button takes the user back to the home page. I don't believe this is where we should be leading the user - for accessibility reasons (more about that below). As I previously mentioned, there is already a way to prevent hacked form submission using ReCAPTCHA. I am not one to usually developing multiple ways of achieving a given outcome as they often end up conflicting with each other resulting in confusion for administrators.

At some point in our discussions, someone (might have been you?) briefly brought up another use case that I had not considered: What happens if a logged-in user doesn't finish writing their message in time and their session times out before they submit the form?

The way you've coded it, they would:

1. Be notified that their session had timed out
2. Be provided with a Continue button which would take them back to the Home page.

The problem with this approach is that you are telling them that they need to login again. Unless your login form is on the home page, they need to go to the login page, not the home page. Even once they login, you don't know what they may of had to go navigate through in order to find the form they are trying to submit in the first place. Forms can sometimes be buried quite deep in a website. The unfortunate user then needs to find their way back to the form where this whole thing first started and then type up their message again. For people with accessibility issues, this can be an especially challenging and time consuming process. And even if they get back to the form, there is no guaranty that their session won't timeout again while they are typing up a new message. This is the equivalent of your computer rebooting and you loosing your work each time it happens. Not fun at all.

So what might be a better and more accessible friendly solution? You've probably noticed by now that, when a Moodle session times-out, users are typically redirected to the login page, just as you originally proposed (yes, I am now agreeing with your approach). Once they login, their action should hopefully be carried out without loosing any information. I think it is possible here but it might require easing the POST action restriction for logged-in users since I believe the login form forward these fields as a GET type action. Worst case is, if that is not possible, I would at the very least hope that the login page would to redirect the user back to the page/form from where they came before you forced them to login again. In this case, that would simply be the original referrer page. Fortunately, if you use the correct Moodle API function, the login page handles a lot of what I just described automatically for you including displaying a message that their session timed-out and all of the redirections. You can find examples of how to do this in other parts of Moodle core, documentation and other plugins.

The solution you are creating will benefit both your use case (requiring users to be logged-in) and the one I described above. In this situation, our objectives are in alignment which is why I am backing you up, trying to encourage you to keep at it and to not give up.

Are you familiar with the Web Content Accessibility Guidelines ([WCAG 2.0](https://www.w3.org/WAI/WCAG20/quickref/))?. If you plan on doing web development into the future, you should become familiar with this standard because, more and more, it is becoming an essential part of web development. A growing number of organizations, states/provinces and even countries are mandating that websites meet these guidelines at a level A and AA. The U.S. has their section 508 which is more of a subset of WCAG 2.0 however, since Moodle is used around the world, you should aim to meet WCAG 2.0 level AA.

Again, let me know if you have any questions. I am always happy to help out a fellow Moodle developer whenever I can.

Best regards,

Michael

**Comment by jezhops** [comment]
Hi Michael,

Would it be possibel to do the following:

1) Fix outstanding issues with coding sytel
2) Alter the link for the "you need to log in" message to point back to the login page
3) Pass the link back to the HTTP referer (which should be the form from where the submission was made) to the login page meaning after login the user is redirected back to the form?

I dont think there is much point in trying to pass the submitted data back to the form as that would also required the form to be able to process those values and I dont think there is a way to do that in Moodle Page / Book which is where these forms would be created?

**Comment by jezhops** [comment]
Hi Michael,

Regards your comments "it might require easing the POST action restriction for logged-in users since I believe the login form forward these fields as a GET type action" take a look around line 271 of /login/index.php 

`/// First, let's remember where the user was trying to get to before they got here

if (empty($SESSION->wantsurl)) {
    $SESSION->wantsurl = null;
    $referer = get_local_referer(false);
    if ($referer &&
            $referer != $CFG->wwwroot &&
            $referer != $CFG->wwwroot . '/' &&
            $referer != $CFG->httpswwwroot . '/login/' &&
            strpos($referer, $CFG->httpswwwroot . '/login/?') !== 0 &&
            strpos($referer, $CFG->httpswwwroot . '/login/index.php') !== 0) { // There might be some extra params such as ?lang=.
        $SESSION->wantsurl = $referer;
    }
}`

For that to work we I think we would need to send all values as a GET request to the local plugin so that the HTTP referer could bounce the user back to the submission form and send the message.

The problem with that could be the size of the fields.

To be honest I think all this maybe overkill. I dont think the chances of a users session timing out between loading a form inside a Moodle course and them hitting "submit" in that form is very high at all.

I dont think we would have any issues running that option as it is on a large productive site (30,000 users).

The other point is this is an option in the admin settings which could be defaulted to "off" if you think it is going to be problematic?

**Comment by kmoouni** [comment]
Hi Michael
So to be clear, the latest version in the kmoouni fork does:

loginrequired is defaulted to off (so there is no change of functionality by installing)

### Within moodle:
	Without loginrequired:
		If you are logged into moodle (real or guest) you get a message of "Message Sent" and the continue button sends you to the front page.  This is no change from the plugins existing behaviour, the loginrequired has no effect (as expected)
	
	With loginrequired:
		If you are a guest in moodle you get the "Failed to send e-mail" and the continue button sends you to the front page. This is new behaviour, but consistent with existing response.
		If you are logged into moodle you get a message of "Message Sent" and the continue button sends you to the front page, ie the existing behaviour.

### From outside of moodle with spoofing:
	Without loginrequired:
		You get a message of "Message Sent" and the continue button sends you to the front page.  This is no change from the plugins existing behaviour - this is the  security issue this change is trying to fix.
		
	With loginrequired:
		You get the "Failed to send e-mail" and the continue button sends you to the front page.  This is new behaviour  to address the security, but consistent with existing responses.

Well that's the behaviour on my test 3.2 moodle... hopefully the same elsewhere :)
		
The 9 extra code lines in index.php pass the moodle Code Checker and I believe follow style or at least consistent with the rest of the code. It doesnt seem to throw debug messages.
-------

While I can see the value of thinking about where the continue button goes, I'm rather trying to focus on fixing the security issue with minimal code intervention. So hope you can take the changes, if not we'd hope for a fix at some stage.

**Comment by michael-milette** [comment]
Hi @kmoouni and @jezhops ,

This feature, though not exactly as described, has been added to Contact Form for Moodle. Thank you for your contribution.

It is now available for download on GitHub and will be included in future stable releases on Moodle.org.

Best regards,

Michael

**Pull request closed without merging**
